NSE_FII_DII_URL = "https://www.nseindia.com/api/fiidiiTradeReact"

NIFTY_STRIKE_INTERVAL = 50
SENSEX_STRIKE_INTERVAL = 100

COLOR_BULLISH = "#00ff88"
COLOR_BEARISH = "#ff4444"
COLOR_NEUTRAL = "#00d4ff"
COLOR_WARNING = "#ffaa00"
